### ISSUE TITLE
TypeError: undefined is not an object (evaluating 't.type') when using satori-html with Bun

### ISSUE THREAD

**Issue by Syrup** [natemoo-re/satori-html#24]
I encountered a `TypeError: undefined is not an object (evaluating 't.type')` error when using the `satori-html` library with Bun. This issue does not occur when using Node.js.

### Error Details
```log
1 | import{ELEMENT_NODE as f,TEXT_NODE as _,walkSync as j}from"./index.js";var w={attribute:/\[\s*(?:(?<namespace>\*|[-\w\P{ASCII}]*)\|)?(?<name>[-\w\P{ASCII}]+)/gu,id:/#(?<name>[-\w\P{ASCII}]+)/gu,class:/\.(?<name>[-\w\P{ASCII}]+)/gu,comma:/\s*,\s*/g,combinator:/\s*[\s>+~]\s*/g,"pseudo-element":/::(?<name>[-\w\P{ASCII}]+)(?:\((?<argument>¶*)\))?/gu,"pseudo-class":/:(?<name>[-\w\P{ASCII}]+)(?:\((?<argument>¶*)\))?/gu,universal:/(?:(?<namespace>\*|[-\w\P{ASCII}]*)\|)?\*/gu,type:/(?:(?<namespace>\*|[-\w\P{ASCII}]*)\|)?(?<name>[-\w\P{ASCII}]+)/gu},v=new Set(["combinator","comma"]),A=new Set(["not","is","where","has","matches","-moz-any","-webkit-any","nth-child","nth-last-child"]),E=/(?<index>[\dn+-]+)\s+of\s+(?<subtree>.+)/,k={"nth-child":E,"nth-last-child":E},T=t=>{switch(t){case"pseudo-element":case"pseudo-class":return new RegExp(w[t].source.replace("(?<argument>\xB6*)","(?<argument>.*)"),"gu");default:return w[t]}};function M(t,n){l | ... truncated

TypeError: undefined is not an object (evaluating 't.type')
      at S (D:\Projects\Sulfur\node_modules\ultrahtml\dist\selector.js:1:5712)
      at D:\Projects\Sulfur\node_modules\ultrahtml\dist\selector.js:1:6177
      at D:\Projects\Sulfur\node_modules\ultrahtml\dist\selector.js:1:4783
      at D:\Projects\Sulfur\node_modules\ultrahtml\dist\selector.js:1:4896
      at visit (D:\Projects\Sulfur\node_modules\ultrahtml\dist\index.js:1:2544)
      at visit (D:\Projects\Sulfur\node_modules\ultrahtml\dist\index.js:1:2648)
      at C (D:\Projects\Sulfur\node_modules\ultrahtml\dist\selector.js:1:4861)
      at D:\Projects\Sulfur\node_modules\ultrahtml\dist\transformers\inline.js:2:514
      at html (D:\Projects\Sulfur\node_modules\satori-html\dist\index.js:68:5)

Bun v1.1.31 (Windows x64)
```

### Steps to Reproduce
1. Use the following code:
```ts
import satori from "satori";
import { html } from "satori-html";

const markup = html`
  <div style="color: black;">hello, world</div>
`;

const inter = await fetch(
  "https://og-playground.vercel.app/inter-latin-ext-400-normal.woff"
).then((res) => res.arrayBuffer());

const app = await satori(markup, {
  width: 934,
  height: 282,
  fonts: [
    {
      name: "Inter",
      weight: 400,
      style: "normal",
      data: inter,
    },
  ],
});
```
2. Run code using bun

### Environment
- Bun: v1.1.31
- OS: Windows 10

**Comment by VityaSchel** [comment]
It uses ultrahtml under the hood, see https://github.com/natemoo-re/ultrahtml/issues/66

**Comment by VityaSchel** [comment]
Apparently setting `useObjectSyntax` to false in dist/index.js does fix the issue, but all inline CSS styles are completely disabled. I confirmed that Tailwind styles still work

The patch:
```patch
diff --git a/dist/index.js b/dist/index.js
index 2c4ee6ed1d743d30d4f436b31c324f20ca927966..3cb7214df6c8ea79a085ed5dfab29f1637cff799 100644
--- a/dist/index.js
+++ b/dist/index.js
@@ -30,7 +30,7 @@ const TW_NAMES = new Set([
     `tracking-`,
     `z-`,
 ]);
-const inliner = inlineCSS({ useObjectSyntax: true });
+const inliner = inlineCSS({ useObjectSyntax: false });
 const tw = (doc) => {
     walkSync(doc, (node) => {
         if (node.type !== ELEMENT_NODE)

```

add to package.json:
```json
"patchedDependencies": {
  "satori-html@0.3.2": "patches/satori-html@0.3.2.patch"
}
```

**Comment by aslak01** [comment]
Just ran into the same issue and @VityaSchel's patch worked for me too.

**Comment by VityaSchel** [comment]
I ended up using node.js by the way. Tailwind support is very limited

**Comment by kingychiu** [comment]
👋 We ran into the same `t.type` error using satori-html under Bun — sharing in case it's related.

For us it seemed to come from `ultrahtml`'s bundled `parsel-js`. satori-html's inline transformer (`useObjectSyntax`) seeds a `:where([style])` selector, and parsing functional pseudo-classes (`:where()/:is()/:not()`) crashes under Bun/JSC because parsel's literal-string `source.replace('(?<argument>¶*)', …)` doesn't match — `.source` escapes the `¶` to `\u00B6` on JavaScriptCore — so the argument comes back empty and `subtree` is never set.

This PR fixed it for our project: **LeaVerou/parsel#86**. 🙏

**Temporary fix until it lands**, with `patch-package`:

1. `npm i -D patch-package`
2. In `node_modules/ultrahtml/dist/selector.js`:
   ```diff
   - ...source.replace("(?<argument>¶*)","(?<argument>.*)")
   + ...source.replace(/\(\?<argument>[^)]*\)/,"(?<argument>.*)")
   ```
3. `npx patch-package ultrahtml` (commit `patches/ultrahtml+1.6.0.patch`)
4. In `package.json`:
   ```json
   {
     "scripts": { "postinstall": "patch-package" },
     "devDependencies": { "patch-package": "^8.0.1" }
   }
   ```
